Repository zifter/clickhouse-migrations, pull requests merged in 2023-09, with the labels that each got.

#16 Logging configuration fix
  src/clickhouse_migrations/clickhouse_cluster.py
  src/clickhouse_migrations/cmd.py
  src/clickhouse_migrations/migrator.py
  src/tests/test_log_level.py
  tox.ini
Labels: size/M

#18 Use parameterized for launching table tests
  .github/workflows/ci.yaml
  Makefile
  requirements-test.txt
  src/tests/conftest.py
  src/tests/test_clickhouse_migration.py
  src/tests/test_log_level.py
  tox.ini
Labels: size/L

#17 Cluster support
  README.md
  dev/users.xml
  src/clickhouse_migrations/clickhouse_cluster.py
  src/clickhouse_migrations/cmd.py
  src/clickhouse_migrations/migrator.py
  src/tests/test_cluster_support.py
  tox.ini
Labels: size/L

#19 Add support of python 3.12
  .github/workflows/ci.yaml
  Makefile
  setup.cfg
  src/clickhouse_migrations/__init__.py
  tox.ini
Labels: size/S

#20 Dry run mode
  src/clickhouse_migrations/clickhouse_cluster.py
  src/clickhouse_migrations/cmd.py
  src/clickhouse_migrations/migrator.py
  src/tests/test_dryrun.py
Labels: size/L
